# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: code_drops

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
